const actionTypes = {
  CHANGE_TYPE: "CHANGE_TYPE",
  ADD_OXYGEN: "ADD_OXYGEN",
  ADD_BEDS: "ADD_BEDS",
  ADD_MEDS: "ADD_MEDS",
  ADD_PLASMA: "ADD_PLASMA",
  ADD_AMBULANCE: "ADD_AMBULANCE",
  TOGGLE_LOADING: "TOGGLE_LOADING",
  TOGGLE_ERROR: "TOGGLE_ERROR",
  TOGGLE_TABLE: "TOGGLE_TABLE",
  SELECT_RESOURCE: "SELECT_RESOURCE",
  SELECT_STATE: "SELECT_STATE",
  SELECT_CITY: "SELECT_CITY",
  SELECT_BGROUP: "SELECT_BGROUP",
  PLASMA_SELECT: "PLASMA_SELECT",
};

export default actionTypes;