const actionTypes = {
    CHANGE_TYPE: "CHANGE_TYPE",
    ADD_OXYGEN: "ADD_OXYGEN",
    ADD_BEDS: "ADD_BEDS",
    ADD_MEDS: "ADD_MEDS",
    ADD_PLASMA: "ADD_PLASMA",
    ADD_AMBULANCE: "ADD_AMBULANCE",
    TOGGLE_LOADING: "TOGGLE_LOADING",
    TOGGLE_ERROR: "TOGGLE_ERROR"
}

export default actionTypes;